// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run DDL, which is unreliable through the Supabase
    // transaction pooler — use the direct connection for the CLI.
    // The app itself (lib/prisma.ts) uses the pooled DATABASE_URL instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
